<a href="https://colab.research.google.com/github/Shk-tech/my-colab-learning-material/blob/main/2507_korea_numpy_ex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#numpy 행렬 라이브러리
#행렬 연산을 처리할 수 있다.
import numpy as np

In [ ]:
# 1. 원소별 연사 element-wise operation
a = np.array([1, 2, 3, 4])
a * 3

array([ 3,  6,  9, 12])

In [ ]:
# -> 사실 map 연산이었네?
a = [1, 2, 3]
# b = [3, 5, 7]
b = []
for ai in a:
    b.append(ai * 2 + 1)

b = [ai * 2 + 1 for ai in a]

list(map(lambda x : 2 * x + 1, a))

[3, 5, 7]

In [ ]:
a = np.array(a)
b = a * 2 + 1
b

# int a[3] = {1, 2, 3}
# for (int i = 0; i < 3; i++)
# {
#     b[i] = a[i] * 2 + 1;
# }

array([3, 5, 7])

In [ ]:
a = np.array([[1, 2], [3, 4]])
a * a

array([[ 1,  4],
       [ 9, 16]])

In [ ]:
a @ a

array([[ 7, 10],
       [15, 22]])

In [ ]:
a ** 2 # element-wise pow

array([[ 1,  4],
       [ 9, 16]])

In [ ]:
np.log(1)

np.float64(0.0)

In [ ]:
np.log(a)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [ ]:
# 파이썬이 느리지만 느리게 코딩하면 안 된다 ... -> numpy

In [ ]:
# 이미지 -> 행렬
# [640, 480] 행렬....